version: "3.9"

volumes:
  postgres_data:

networks:
  ide_net:
    driver: bridge

services:

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER:     johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB:       mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ide_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U johndoe -d mydb"]
      interval: 5s
      timeout:  5s
      retries:  10

  master:
    build:
      context:    ./server/master
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/master/.env.docker
    volumes:
      - ./server/projects:/app/projects
    ports:
      - "3000:3000"
    networks:
      - ide_net

  worker:
    build:
      context:    ./server/worker
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - master
    env_file:
      - ./server/worker/.env.docker
    privileged: true
    environment:
      DOCKER_HOST:       unix:///var/run/docker.sock
      HOST_PROJECTS_DIR: ${PWD}/projects
    volumes:
      - ./server/projects:/app/projects
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4000:4000"
      - "5000:5000"
    networks:
      - ide_net

  frontend:
    build:
      context:    ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL:             http://localhost:3000
        VITE_WORKER_TERMINAL_URL: ws://localhost:4000
        VITE_WORKER_EDITOR_URL:   http://localhost:5000
    restart: unless-stopped
    depends_on:
      - master
      - worker
    env_file:
      - ./frontend/.env.docker
    ports:
      - "8080:8080"
    networks:
      - ide_net